# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Personal Blog
tagline:          'Deepshikha'
description:      'My GitHub Repo <a href="https://github.com/Deepshikha05" target="_blank">Here</a>'
url:              https://github.com/Deepshikha05
baseurl:          https://deepshikha05.github.io/

author:
  name:           'Deepshikha Sethi'
  url:            https://github.com/Deepshikha05
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Deepshikha05
